name: my first 
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest 
    steps:
      - name: print hello
        run : echo "hello"
      - name: good bye
        run: echo "done"
     
  
